### ISSUE TITLE
Clean up transcription

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/mess-gpt-preprocessor#1]
## Description

Remove the types of strings described bellow.

## TODO

- [x] Remove parts
  - [x] Line numbers: `^{[0-9]+}\s`
- [x] Remove lines
  - [x] URLs `http(s)?:\/\/`
  - [x] Message deletion: `(C|c)ofn(ięto|ęła)\swys(y)?łanie\swiadomości`
  - [x] Deleted media: `Załącznik niedostępnyTen załącznik mógł zostać usunięty lub`
  - [x] Msg shares: `(Przekazano wiadomość|przekazuje wiadomość)`
  - [x] Replies: `(Odpowiedziałeś(aś)\s|Oryginalna wiadomość:|Użytkownik  odpisał Ci|odpowiedział)`
  - [x] Empty lines: `^(|\s+)$`
